/* Auto-generated by genmsg_cpp for file /home/phil/fuerte_workspace/sandbox/AU_UAV_stack/AU_UAV_ROS/srv/ClearCoordinator.srv */
#ifndef AU_UAV_ROS_SERVICE_CLEARCOORDINATOR_H
#define AU_UAV_ROS_SERVICE_CLEARCOORDINATOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace AU_UAV_ROS
{
template <class ContainerAllocator>
struct ClearCoordinatorRequest_ {
  typedef ClearCoordinatorRequest_<ContainerAllocator> Type;

  ClearCoordinatorRequest_()
  : hello()
  {
  }

  ClearCoordinatorRequest_(const ContainerAllocator& _alloc)
  : hello(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hello_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  hello;


  typedef boost::shared_ptr< ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ClearCoordinatorRequest
typedef  ::AU_UAV_ROS::ClearCoordinatorRequest_<std::allocator<void> > ClearCoordinatorRequest;

typedef boost::shared_ptr< ::AU_UAV_ROS::ClearCoordinatorRequest> ClearCoordinatorRequestPtr;
typedef boost::shared_ptr< ::AU_UAV_ROS::ClearCoordinatorRequest const> ClearCoordinatorRequestConstPtr;


template <class ContainerAllocator>
struct ClearCoordinatorResponse_ {
  typedef ClearCoordinatorResponse_<ContainerAllocator> Type;

  ClearCoordinatorResponse_()
  : error()
  {
  }

  ClearCoordinatorResponse_(const ContainerAllocator& _alloc)
  : error(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  error;


  typedef boost::shared_ptr< ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ClearCoordinatorResponse
typedef  ::AU_UAV_ROS::ClearCoordinatorResponse_<std::allocator<void> > ClearCoordinatorResponse;

typedef boost::shared_ptr< ::AU_UAV_ROS::ClearCoordinatorResponse> ClearCoordinatorResponsePtr;
typedef boost::shared_ptr< ::AU_UAV_ROS::ClearCoordinatorResponse const> ClearCoordinatorResponseConstPtr;

struct ClearCoordinator
{

typedef ClearCoordinatorRequest Request;
typedef ClearCoordinatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ClearCoordinator
} // namespace AU_UAV_ROS

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "aa1e4c96cf56304cea7e883d117e24f3";
  }

  static const char* value(const  ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xaa1e4c96cf56304cULL;
  static const uint64_t static_value2 = 0xea7e883d117e24f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "AU_UAV_ROS/ClearCoordinatorRequest";
  }

  static const char* value(const  ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string hello\n\
\n\
";
  }

  static const char* value(const  ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eca8b96616c32aacf1be8bbf14c70eba";
  }

  static const char* value(const  ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xeca8b96616c32aacULL;
  static const uint64_t static_value2 = 0xf1be8bbf14c70ebaULL;
};

template<class ContainerAllocator>
struct DataType< ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "AU_UAV_ROS/ClearCoordinatorResponse";
  }

  static const char* value(const  ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string error\n\
\n\
\n\
";
  }

  static const char* value(const  ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.hello);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ClearCoordinatorRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.error);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ClearCoordinatorResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<AU_UAV_ROS::ClearCoordinator> {
  static const char* value() 
  {
    return "3d4ba6c1e7182cfa297a43c7395e613d";
  }

  static const char* value(const AU_UAV_ROS::ClearCoordinator&) { return value(); } 
};

template<>
struct DataType<AU_UAV_ROS::ClearCoordinator> {
  static const char* value() 
  {
    return "AU_UAV_ROS/ClearCoordinator";
  }

  static const char* value(const AU_UAV_ROS::ClearCoordinator&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3d4ba6c1e7182cfa297a43c7395e613d";
  }

  static const char* value(const AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "AU_UAV_ROS/ClearCoordinator";
  }

  static const char* value(const AU_UAV_ROS::ClearCoordinatorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3d4ba6c1e7182cfa297a43c7395e613d";
  }

  static const char* value(const AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "AU_UAV_ROS/ClearCoordinator";
  }

  static const char* value(const AU_UAV_ROS::ClearCoordinatorResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // AU_UAV_ROS_SERVICE_CLEARCOORDINATOR_H

