(cl:in-package AU_UAV_Team1-srv)
(cl:export '(STARTINGLATITUDE-VAL
          STARTINGLATITUDE
          STARTINGLONGITUDE-VAL
          STARTINGLONGITUDE
          STARTINGALTITUDE-VAL
          STARTINGALTITUDE
          STARTINGBEARING-VAL
          STARTINGBEARING
          REQUESTEDID-VAL
          REQUESTEDID
          PLANEID-VAL
          PLANEID
))